#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleTraveller.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LittleTravellersDB")]
	public partial class LittleTravellerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void Insertstate(state instance);
    partial void Updatestate(state instance);
    partial void Deletestate(state instance);
    partial void InsertItem(Item instance);
    partial void UpdateItem(Item instance);
    partial void DeleteItem(Item instance);
    #endregion
		
		public LittleTravellerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LittleTravellersDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LittleTravellerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LittleTravellerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LittleTravellerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LittleTravellerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<state> states
		{
			get
			{
				return this.GetTable<state>();
			}
		}
		
		public System.Data.Linq.Table<Item> Items
		{
			get
			{
				return this.GetTable<Item>();
			}
		}
		
		public System.Data.Linq.Table<Color> Colors
		{
			get
			{
				return this.GetTable<Color>();
			}
		}
		
		public System.Data.Linq.Table<Season> Seasons
		{
			get
			{
				return this.GetTable<Season>();
			}
		}
		
		public System.Data.Linq.Table<Design> Designs
		{
			get
			{
				return this.GetTable<Design>();
			}
		}
		
		public System.Data.Linq.Table<SizeType> SizeTypes
		{
			get
			{
				return this.GetTable<SizeType>();
			}
		}
		
		public System.Data.Linq.Table<Size> Sizes
		{
			get
			{
				return this.GetTable<Size>();
			}
		}
		
		public System.Data.Linq.Table<StyleType> StyleTypes
		{
			get
			{
				return this.GetTable<StyleType>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _CustomerNum;
		
		private string _CompanyName;
		
		private string _BillToAddr1;
		
		private string _BillToAddr2;
		
		private string _BillToCity;
		
		private string _BillToState;
		
		private string _BillToZip5;
		
		private string _BillToZip4;
		
		private string _BillToPhone;
		
		private string _BillToFax;
		
		private string _email;
		
		private string _ShipToAddr1;
		
		private string _ShipToAddr2;
		
		private string _ShipToCity;
		
		private string _ShipToState;
		
		private string _ShipToZip5;
		
		private string _ShipToZip4;
		
		private string _ShipToPhone;
		
		private string _ShipToFax;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerNumChanging(short value);
    partial void OnCustomerNumChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnBillToAddr1Changing(string value);
    partial void OnBillToAddr1Changed();
    partial void OnBillToAddr2Changing(string value);
    partial void OnBillToAddr2Changed();
    partial void OnBillToCityChanging(string value);
    partial void OnBillToCityChanged();
    partial void OnBillToStateChanging(string value);
    partial void OnBillToStateChanged();
    partial void OnBillToZip5Changing(string value);
    partial void OnBillToZip5Changed();
    partial void OnBillToZip4Changing(string value);
    partial void OnBillToZip4Changed();
    partial void OnBillToPhoneChanging(string value);
    partial void OnBillToPhoneChanged();
    partial void OnBillToFaxChanging(string value);
    partial void OnBillToFaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnShipToAddr1Changing(string value);
    partial void OnShipToAddr1Changed();
    partial void OnShipToAddr2Changing(string value);
    partial void OnShipToAddr2Changed();
    partial void OnShipToCityChanging(string value);
    partial void OnShipToCityChanged();
    partial void OnShipToStateChanging(string value);
    partial void OnShipToStateChanged();
    partial void OnShipToZip5Changing(string value);
    partial void OnShipToZip5Changed();
    partial void OnShipToZip4Changing(string value);
    partial void OnShipToZip4Changed();
    partial void OnShipToPhoneChanging(string value);
    partial void OnShipToPhoneChanged();
    partial void OnShipToFaxChanging(string value);
    partial void OnShipToFaxChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerNum", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short CustomerNum
		{
			get
			{
				return this._CustomerNum;
			}
			set
			{
				if ((this._CustomerNum != value))
				{
					this.OnCustomerNumChanging(value);
					this.SendPropertyChanging();
					this._CustomerNum = value;
					this.SendPropertyChanged("CustomerNum");
					this.OnCustomerNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToAddr1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BillToAddr1
		{
			get
			{
				return this._BillToAddr1;
			}
			set
			{
				if ((this._BillToAddr1 != value))
				{
					this.OnBillToAddr1Changing(value);
					this.SendPropertyChanging();
					this._BillToAddr1 = value;
					this.SendPropertyChanged("BillToAddr1");
					this.OnBillToAddr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToAddr2", DbType="NVarChar(50)")]
		public string BillToAddr2
		{
			get
			{
				return this._BillToAddr2;
			}
			set
			{
				if ((this._BillToAddr2 != value))
				{
					this.OnBillToAddr2Changing(value);
					this.SendPropertyChanging();
					this._BillToAddr2 = value;
					this.SendPropertyChanged("BillToAddr2");
					this.OnBillToAddr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToCity", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BillToCity
		{
			get
			{
				return this._BillToCity;
			}
			set
			{
				if ((this._BillToCity != value))
				{
					this.OnBillToCityChanging(value);
					this.SendPropertyChanging();
					this._BillToCity = value;
					this.SendPropertyChanged("BillToCity");
					this.OnBillToCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToState", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string BillToState
		{
			get
			{
				return this._BillToState;
			}
			set
			{
				if ((this._BillToState != value))
				{
					this.OnBillToStateChanging(value);
					this.SendPropertyChanging();
					this._BillToState = value;
					this.SendPropertyChanged("BillToState");
					this.OnBillToStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToZip5", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string BillToZip5
		{
			get
			{
				return this._BillToZip5;
			}
			set
			{
				if ((this._BillToZip5 != value))
				{
					this.OnBillToZip5Changing(value);
					this.SendPropertyChanging();
					this._BillToZip5 = value;
					this.SendPropertyChanged("BillToZip5");
					this.OnBillToZip5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToZip4", DbType="NChar(10)")]
		public string BillToZip4
		{
			get
			{
				return this._BillToZip4;
			}
			set
			{
				if ((this._BillToZip4 != value))
				{
					this.OnBillToZip4Changing(value);
					this.SendPropertyChanging();
					this._BillToZip4 = value;
					this.SendPropertyChanged("BillToZip4");
					this.OnBillToZip4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToPhone", DbType="NVarChar(50)")]
		public string BillToPhone
		{
			get
			{
				return this._BillToPhone;
			}
			set
			{
				if ((this._BillToPhone != value))
				{
					this.OnBillToPhoneChanging(value);
					this.SendPropertyChanging();
					this._BillToPhone = value;
					this.SendPropertyChanged("BillToPhone");
					this.OnBillToPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToFax", DbType="NVarChar(50)")]
		public string BillToFax
		{
			get
			{
				return this._BillToFax;
			}
			set
			{
				if ((this._BillToFax != value))
				{
					this.OnBillToFaxChanging(value);
					this.SendPropertyChanging();
					this._BillToFax = value;
					this.SendPropertyChanged("BillToFax");
					this.OnBillToFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToAddr1", DbType="NVarChar(50)")]
		public string ShipToAddr1
		{
			get
			{
				return this._ShipToAddr1;
			}
			set
			{
				if ((this._ShipToAddr1 != value))
				{
					this.OnShipToAddr1Changing(value);
					this.SendPropertyChanging();
					this._ShipToAddr1 = value;
					this.SendPropertyChanged("ShipToAddr1");
					this.OnShipToAddr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToAddr2", DbType="NVarChar(50)")]
		public string ShipToAddr2
		{
			get
			{
				return this._ShipToAddr2;
			}
			set
			{
				if ((this._ShipToAddr2 != value))
				{
					this.OnShipToAddr2Changing(value);
					this.SendPropertyChanging();
					this._ShipToAddr2 = value;
					this.SendPropertyChanged("ShipToAddr2");
					this.OnShipToAddr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToCity", DbType="NVarChar(50)")]
		public string ShipToCity
		{
			get
			{
				return this._ShipToCity;
			}
			set
			{
				if ((this._ShipToCity != value))
				{
					this.OnShipToCityChanging(value);
					this.SendPropertyChanging();
					this._ShipToCity = value;
					this.SendPropertyChanged("ShipToCity");
					this.OnShipToCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToState", DbType="NChar(10)")]
		public string ShipToState
		{
			get
			{
				return this._ShipToState;
			}
			set
			{
				if ((this._ShipToState != value))
				{
					this.OnShipToStateChanging(value);
					this.SendPropertyChanging();
					this._ShipToState = value;
					this.SendPropertyChanged("ShipToState");
					this.OnShipToStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToZip5", DbType="NChar(10)")]
		public string ShipToZip5
		{
			get
			{
				return this._ShipToZip5;
			}
			set
			{
				if ((this._ShipToZip5 != value))
				{
					this.OnShipToZip5Changing(value);
					this.SendPropertyChanging();
					this._ShipToZip5 = value;
					this.SendPropertyChanged("ShipToZip5");
					this.OnShipToZip5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToZip4", DbType="NChar(10)")]
		public string ShipToZip4
		{
			get
			{
				return this._ShipToZip4;
			}
			set
			{
				if ((this._ShipToZip4 != value))
				{
					this.OnShipToZip4Changing(value);
					this.SendPropertyChanging();
					this._ShipToZip4 = value;
					this.SendPropertyChanged("ShipToZip4");
					this.OnShipToZip4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToPhone", DbType="NVarChar(50)")]
		public string ShipToPhone
		{
			get
			{
				return this._ShipToPhone;
			}
			set
			{
				if ((this._ShipToPhone != value))
				{
					this.OnShipToPhoneChanging(value);
					this.SendPropertyChanging();
					this._ShipToPhone = value;
					this.SendPropertyChanged("ShipToPhone");
					this.OnShipToPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToFax", DbType="NVarChar(50)")]
		public string ShipToFax
		{
			get
			{
				return this._ShipToFax;
			}
			set
			{
				if ((this._ShipToFax != value))
				{
					this.OnShipToFaxChanging(value);
					this.SendPropertyChanging();
					this._ShipToFax = value;
					this.SendPropertyChanged("ShipToFax");
					this.OnShipToFaxChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.states")]
	public partial class state : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public state()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)", IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item")]
	public partial class Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sku;
		
		private string _seasonID;
		
		private string _colorID;
		
		private string _color2ID;
		
		private string _color3ID;
		
		private string _sizeType;
		
		private string _size;
		
		private string _styleTypeID;
		
		private string _designID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnskuChanging(string value);
    partial void OnskuChanged();
    partial void OnseasonIDChanging(string value);
    partial void OnseasonIDChanged();
    partial void OncolorIDChanging(string value);
    partial void OncolorIDChanged();
    partial void Oncolor2IDChanging(string value);
    partial void Oncolor2IDChanged();
    partial void Oncolor3IDChanging(string value);
    partial void Oncolor3IDChanged();
    partial void OnsizeTypeChanging(string value);
    partial void OnsizeTypeChanged();
    partial void OnsizeChanging(string value);
    partial void OnsizeChanged();
    partial void OnstyleTypeIDChanging(string value);
    partial void OnstyleTypeIDChanged();
    partial void OndesignIDChanging(string value);
    partial void OndesignIDChanged();
    #endregion
		
		public Item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sku", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sku
		{
			get
			{
				return this._sku;
			}
			set
			{
				if ((this._sku != value))
				{
					this.OnskuChanging(value);
					this.SendPropertyChanging();
					this._sku = value;
					this.SendPropertyChanged("sku");
					this.OnskuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seasonID", DbType="NChar(10)")]
		public string seasonID
		{
			get
			{
				return this._seasonID;
			}
			set
			{
				if ((this._seasonID != value))
				{
					this.OnseasonIDChanging(value);
					this.SendPropertyChanging();
					this._seasonID = value;
					this.SendPropertyChanged("seasonID");
					this.OnseasonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colorID", DbType="NChar(10)")]
		public string colorID
		{
			get
			{
				return this._colorID;
			}
			set
			{
				if ((this._colorID != value))
				{
					this.OncolorIDChanging(value);
					this.SendPropertyChanging();
					this._colorID = value;
					this.SendPropertyChanged("colorID");
					this.OncolorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color2ID", DbType="NChar(10)")]
		public string color2ID
		{
			get
			{
				return this._color2ID;
			}
			set
			{
				if ((this._color2ID != value))
				{
					this.Oncolor2IDChanging(value);
					this.SendPropertyChanging();
					this._color2ID = value;
					this.SendPropertyChanged("color2ID");
					this.Oncolor2IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color3ID", DbType="NChar(10)")]
		public string color3ID
		{
			get
			{
				return this._color3ID;
			}
			set
			{
				if ((this._color3ID != value))
				{
					this.Oncolor3IDChanging(value);
					this.SendPropertyChanging();
					this._color3ID = value;
					this.SendPropertyChanged("color3ID");
					this.Oncolor3IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sizeType", DbType="NChar(10)")]
		public string sizeType
		{
			get
			{
				return this._sizeType;
			}
			set
			{
				if ((this._sizeType != value))
				{
					this.OnsizeTypeChanging(value);
					this.SendPropertyChanging();
					this._sizeType = value;
					this.SendPropertyChanged("sizeType");
					this.OnsizeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="NChar(10)")]
		public string size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this.OnsizeChanging(value);
					this.SendPropertyChanging();
					this._size = value;
					this.SendPropertyChanged("size");
					this.OnsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_styleTypeID", DbType="NChar(10)")]
		public string styleTypeID
		{
			get
			{
				return this._styleTypeID;
			}
			set
			{
				if ((this._styleTypeID != value))
				{
					this.OnstyleTypeIDChanging(value);
					this.SendPropertyChanging();
					this._styleTypeID = value;
					this.SendPropertyChanged("styleTypeID");
					this.OnstyleTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designID", DbType="NChar(10)")]
		public string designID
		{
			get
			{
				return this._designID;
			}
			set
			{
				if ((this._designID != value))
				{
					this.OndesignIDChanging(value);
					this.SendPropertyChanging();
					this._designID = value;
					this.SendPropertyChanged("designID");
					this.OndesignIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Color")]
	public partial class Color
	{
		
		private string _colorCode;
		
		public Color()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colorCode", DbType="NChar(10)")]
		public string colorCode
		{
			get
			{
				return this._colorCode;
			}
			set
			{
				if ((this._colorCode != value))
				{
					this._colorCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Season")]
	public partial class Season
	{
		
		private string _SeasonCode;
		
		public Season()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeasonCode", DbType="NChar(10)")]
		public string SeasonCode
		{
			get
			{
				return this._SeasonCode;
			}
			set
			{
				if ((this._SeasonCode != value))
				{
					this._SeasonCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Design")]
	public partial class Design
	{
		
		private int _ID;
		
		private string _desc;
		
		public Design()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="NVarChar(50)")]
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				if ((this._desc != value))
				{
					this._desc = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SizeType")]
	public partial class SizeType
	{
		
		private string _sizeTypeName;
		
		public SizeType()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sizeTypeName", DbType="NVarChar(50)")]
		public string sizeTypeName
		{
			get
			{
				return this._sizeTypeName;
			}
			set
			{
				if ((this._sizeTypeName != value))
				{
					this._sizeTypeName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Size")]
	public partial class Size
	{
		
		private string _sizeTypeName;
		
		private string _sizeVal;
		
		public Size()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sizeTypeName", DbType="NVarChar(50)")]
		public string sizeTypeName
		{
			get
			{
				return this._sizeTypeName;
			}
			set
			{
				if ((this._sizeTypeName != value))
				{
					this._sizeTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sizeVal", DbType="NChar(10)")]
		public string sizeVal
		{
			get
			{
				return this._sizeVal;
			}
			set
			{
				if ((this._sizeVal != value))
				{
					this._sizeVal = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StyleType")]
	public partial class StyleType
	{
		
		private int _ID;
		
		private string _DESC;
		
		public StyleType()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DESC]", Storage="_DESC", DbType="NVarChar(50)")]
		public string DESC
		{
			get
			{
				return this._DESC;
			}
			set
			{
				if ((this._DESC != value))
				{
					this._DESC = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
